
module.exports = {
    TIMER_UPDATE: 'TIMER_UPDATE',
    TIMER_START: 'TIMER_START',
    TIMER_STOP: 'TIMER_STOP',
    TIMER_PAUSE: 'TIMER_PAUSE',
    TIMERS_LOAD_ERROR: 'TIMERS_LOAD_ERROR',
    TIMERS_LOAD_SUCCESS: 'TIMERS_LOAD_SUCCESS',
    INITIALIZE_TRAY: 'INITIALIZE_TRAY',
    TIMER_NOT_INIT_ERROR: 'TIMER_NOT_INIT_ERROR',

    REQUEST_TIMER_START: 'REQUEST_TIMER_START',
    REQUEST_TIMER_PAUSE: 'REQUEST_TIMER_PAUSE',
    REQUEST_TIMER_STOP: 'REQUEST_TIMER_STOP',
    STORAGE_FILE: 'storage.json',
}