const TIMER_UPDATE = 'TIMER_UPDATE'
const TIMER_START = 'TIMER_START'
const TIMER_STOP = 'TIMER_STOP'
const TIMER_PAUSE = 'TIMER_PAUSE'
const TIMERS_LOAD_ERROR = 'TIMERS_LOAD_ERROR'
const TIMERS_LOAD_SUCCESS = 'TIMERS_LOAD_SUCCESS'
const INITIALIZE_TRAY = 'INITIALIZE_TRAY'
const TIMER_NOT_INIT_ERROR = 'TIMER_NOT_INIT_ERROR'

const STORAGE_FILE = 'storage.json'

module.exports = {
    TIMER_UPDATE,
    TIMER_START,
    TIMER_STOP,
    TIMER_PAUSE,
    STORAGE_FILE,
    TIMERS_LOAD_ERROR,
    TIMERS_LOAD_SUCCESS,
    INITIALIZE_TRAY,
    TIMER_NOT_INIT_ERROR,
}